# Generated by Django 5.2.7 on 2026-01-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='food_item',
            new_name='food_items',
        ),
    ]
