# Generated by Django 5.2.7 on 2026-01-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_food_item_orderitem_food_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='food_items',
            new_name='food_item',
        ),
    ]
